import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { BrandKit, shortStack } from "@/components/artifacts/Artifacts";
import { CtaBand } from "@/components/examples/CtaBand";
import { ExampleTracker } from "@/components/examples/ExampleTracker";
import { InTheApp } from "@/components/home/InTheApp";
import { PageShell } from "@/components/site/PageShell";
import { formatDate, formatDuration, getRun, hostOf, paletteOf, prdFeatureCount, runs, type Feature } from "@/content/runs";
import { brandFontFamily } from "@/lib/brand-fonts";
import { absoluteUrl } from "@/lib/site";
import { buildBreadcrumbSchema } from "@/lib/structured-data";

type Params = { slug: string };

export function generateStaticParams() {
  return runs.map((r) => ({ slug: r.slug }));
}

export const dynamicParams = false;

const WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"];
function numberWord(n: number) {
  return WORDS[n] ?? String(n);
}

function shortName(title: string) {
  return title.split(":")[0].trim();
}

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { slug } = await params;
  const run = getRun(slug);
  if (!run) return {};
  const name = shortName(run.title);
  const title = `${name} PRD example: ${run.idea}`;
  const description = `A real PRD, competitor research, brand kit, engineering brief, roadmap and ${run.jira.storyCount}-story Jira board for ${name}, generated by Murmur from a ${formatDuration(run.memoSeconds)} voice memo in ${formatDuration(run.runSeconds)}.`;
  return {
    title,
    description,
    alternates: { canonical: `/examples/${slug}` },
    openGraph: { title: `${name}: a real Murmur foundation`, description, url: absoluteUrl(`/examples/${slug}`), type: "article" },
    twitter: { card: "summary_large_image", title: `${name}: a real Murmur foundation`, description },
  };
}

const toc = [
  { id: "memo", label: "Voice memo" },
  { id: "research", label: "Competitor map" },
  { id: "prd", label: "PRD" },
  { id: "brand", label: "Brand kit" },
  { id: "engineering", label: "Tech design" },
  { id: "confluence", label: "Confluence space" },
  { id: "roadmap", label: "Roadmap" },
  { id: "jira", label: "Jira board" },
];

function Section({ id, n, title, children, lead }: { id: string; n: string; title: string; lead?: ReactNode; children: ReactNode }) {
  return (
    <section id={id} aria-labelledby={`${id}-h`} className="scroll-mt-28 border-t border-line pt-12 pb-4 first:border-t-0 first:pt-0">
      <p className="font-mono text-xs text-signal">{n}</p>
      <h2 id={`${id}-h`} className="display-3 mt-2">
        {title}
      </h2>
      {lead ? <p className="lede mt-3 max-w-2xl !text-[1.02rem]">{lead}</p> : null}
      <div className="mt-8">{children}</div>
    </section>
  );
}

function Sub({ children }: { children: ReactNode }) {
  return <h3 className="mb-3 mt-10 text-[1.05rem] font-semibold text-fg first:mt-0">{children}</h3>;
}

function Bullets({ items }: { items: string[] }) {
  return (
    <ul className="grid gap-2">
      {items.map((item) => (
        <li key={item} className="flex gap-3 text-[0.98rem] leading-relaxed text-fg-2">
          <span className="mt-[0.7em] size-1.5 shrink-0 rounded-full bg-fg-3" aria-hidden="true" />
          {item}
        </li>
      ))}
    </ul>
  );
}

function FeatureList({ label, items, tone }: { label: string; items: Feature[]; tone: "must" | "should" | "could" | "wont" }) {
  if (!items.length) return null;
  const toneClass = {
    must: "border-signal/50 bg-signal-soft text-fg",
    should: "border-line-2 bg-surface-2 text-fg",
    could: "border-line bg-surface text-fg-2",
    wont: "border-line bg-surface text-fg-3",
  }[tone];
  return (
    <div className="mt-8">
      <p className="flex items-center gap-2">
        <span className={`rounded-full border px-2.5 py-1 font-mono text-[0.68rem] uppercase tracking-[0.1em] ${toneClass}`}>{label}</span>
        <span className="font-mono text-xs text-fg-3">{items.length}</span>
      </p>
      <ol className="mt-4 grid gap-3">
        {items.map((f) => (
          <li key={f.title} className="rounded-2xl border border-line bg-surface p-4 sm:p-5">
            <p className={`font-medium ${tone === "wont" ? "text-fg-2 line-through decoration-fg-3/50" : "text-fg"}`}>{f.title}</p>
            <p className="mt-1.5 text-[0.95rem] leading-relaxed text-fg-2">{f.description}</p>
            {f.rationale ? (
              <p className="mt-2.5 border-l-2 border-line-2 pl-3 text-[0.88rem] leading-relaxed text-fg-3">
                <span className="font-mono text-[0.66rem] uppercase tracking-[0.1em]">Why · </span>
                {f.rationale}
              </p>
            ) : null}
          </li>
        ))}
      </ol>
    </div>
  );
}

export default async function ExamplePage({ params }: { params: Promise<Params> }) {
  const { slug } = await params;
  const run = getRun(slug);
  if (!run) notFound();

  const name = shortName(run.title);
  const idx = runs.findIndex((r) => r.slug === slug);
  const next = runs[(idx + 1) % runs.length];
  const palette = paletteOf(run);
  const heading = brandFontFamily(run.brand.typography.heading);
  const featureCount = prdFeatureCount(run);
  const allRationales = Object.values(run.prd.features)
    .flat()
    .every((f) => Boolean(f.rationale));

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    headline: `${name} PRD example: ${run.idea}`,
    description: run.prd.oneLiner,
    datePublished: run.runAt,
    dateModified: "2026-09-26",
    author: { "@type": "Organization", name: "SprintZero Studios", url: absoluteUrl("/") },
    publisher: { "@type": "Organization", name: "SprintZero Studios", logo: { "@type": "ImageObject", url: absoluteUrl("/icons/icon-512.png") } },
    mainEntityOfPage: absoluteUrl(`/examples/${slug}`),
    about: ["Product requirements document", "Competitor analysis", "Brand kit", "Technical design document", "Jira backlog"],
  };
  const breadcrumbs = buildBreadcrumbSchema([
    { name: "Murmur", path: "/" },
    { name: "Examples", path: "/examples" },
    { name, path: `/examples/${slug}` },
  ]);

  return (
    <PageShell>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([articleSchema, breadcrumbs]) }} />
      <ExampleTracker slug={slug} />

      {/* Hero, themed with the run's own brand palette */}
      <header className="relative isolate overflow-hidden pb-14 pt-32 sm:pt-40">
        <div aria-hidden="true" className="absolute inset-0 -z-10 opacity-[0.22]" style={{ background: `radial-gradient(60% 70% at 85% 10%, ${run.brand.colorPalette.primary}, transparent 70%), radial-gradient(50% 60% at 10% 90%, ${run.brand.colorPalette.accent}, transparent 70%)` }} />
        <div className="wrap">
          <nav aria-label="Breadcrumb" className="font-mono text-xs text-fg-3">
            <ol className="flex flex-wrap items-center gap-2">
              <li>
                <Link href="/" className="hover:text-fg">
                  Murmur
                </Link>
              </li>
              <li aria-hidden="true">/</li>
              <li>
                <Link href="/examples" className="hover:text-fg">
                  Examples
                </Link>
              </li>
              <li aria-hidden="true">/</li>
              <li aria-current="page" className="text-fg-2">
                {name}
              </li>
            </ol>
          </nav>
          <p className="eyebrow mt-8 flex items-center gap-2">
            <span className="rec-dot text-signal" aria-hidden="true" /> Real Murmur run · {run.category} · unedited output
          </p>
          <h1 className="display-1 balance mt-4 max-w-5xl">
            {name} <span className="serif-accent text-fg-2">PRD, brand kit &amp; Jira board</span>
          </h1>
          <p className="lede mt-5 max-w-3xl">{run.prd.oneLiner}</p>

          <dl className="mt-8 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">
            {[
              ["Voice memo", formatDuration(run.memoSeconds, "clock")],
              ["Run time", formatDuration(run.runSeconds)],
              ["Competitors", String(run.research.competitors.length)],
              ["PRD features", String(featureCount)],
              ["Jira epics", String(run.jira.epicCount)],
              ["Jira stories", String(run.jira.storyCount)],
            ].map(([k, v]) => (
              <div key={k} className="rounded-2xl border border-line bg-surface/70 px-4 py-3 backdrop-blur">
                <dt className="font-mono text-[0.62rem] uppercase tracking-[0.12em] text-fg-3">{k}</dt>
                <dd className="mt-0.5 font-display text-2xl font-semibold tracking-[-0.03em] text-fg">{v}</dd>
              </div>
            ))}
          </dl>
          <p className="mt-4 font-mono text-[0.7rem] text-fg-3">
            Recorded {formatDate(run.recordedAt)} · run {formatDate(run.runAt)} · published with the owner&apos;s permission. Links into the
            owner&apos;s Atlassian site and raw search results are removed.
          </p>
        </div>
      </header>

      <div className="wrap pb-14">
        <InTheApp slug={slug} title={name} />
      </div>

      <div className="wrap pb-10">
        <div className="grid gap-12 lg:grid-cols-[14rem_1fr] xl:grid-cols-[16rem_1fr]">
          {/* TOC */}
          <aside className="hidden lg:block">
            <nav aria-label="On this page" className="sticky top-28">
              <p className="eyebrow">On this page</p>
              <ol className="mt-4 grid gap-1 border-l border-line">
                {toc.map((item, i) => (
                  <li key={item.id}>
                    <a href={`#${item.id}`} className="-ml-px flex gap-3 border-l border-transparent py-1.5 pl-4 text-sm text-fg-2 transition hover:border-signal hover:text-fg">
                      <span className="font-mono text-[0.68rem] text-fg-3">{String(i + 1).padStart(2, "0")}</span>
                      {item.label}
                    </a>
                  </li>
                ))}
              </ol>
              <div className="mt-8 flex gap-1.5" aria-hidden="true">
                {palette.map((c) => (
                  <span key={c.hex} className="h-8 flex-1 rounded-md border border-line" style={{ background: c.hex }} />
                ))}
              </div>
            </nav>
          </aside>

          <article className="min-w-0 max-w-3xl">
            <Section id="memo" n="01" title="The voice memo" lead={`${formatDuration(run.memoSeconds, "clock")} of talking. This is the only input Murmur got.`}>
              <blockquote className="rounded-2xl border border-line bg-surface p-5 text-[1.02rem] leading-[1.75] text-fg-2 sm:p-7">
                <span className="font-serif text-4xl leading-none text-signal">“</span>
                <p className="-mt-3">{run.transcript}</p>
              </blockquote>
              {slug === "fin-matter" ? <p className="mt-3 font-mono text-xs text-fg-3">Excerpt, trimmed for privacy.</p> : null}
            </Section>

            <Section id="research" n="02" title="Competitor map" lead="Live web search for who's already building nearby, with a source link for every competitor.">
              <Sub>Market summary</Sub>
              <p className="text-[0.98rem] leading-relaxed text-fg-2">{run.research.marketSummary}</p>
              <Sub>Competitors</Sub>
              <div className="grid gap-3">
                {run.research.competitors.map((c) => (
                  <div key={c.name} className="rounded-2xl border border-line bg-surface p-4 sm:p-5">
                    <div className="flex flex-wrap items-baseline justify-between gap-2">
                      <p className="font-medium text-fg">{c.name}</p>
                      <a href={c.url} target="_blank" rel="noopener noreferrer nofollow" className="font-mono text-xs text-fg-3 underline decoration-line-2 underline-offset-2 hover:text-signal">
                        {hostOf(c.url)} ↗
                      </a>
                    </div>
                    <p className="mt-2 text-[0.95rem] leading-relaxed text-fg-2">{c.positioning}</p>
                    <div className="mt-4 grid gap-4 sm:grid-cols-2">
                      <div>
                        <p className="font-mono text-[0.64rem] uppercase tracking-[0.12em] text-ok">Strengths</p>
                        <ul className="mt-2 grid gap-1 text-[0.88rem] text-fg-2">
                          {c.strengths.map((s) => (
                            <li key={s}>+ {s}</li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <p className="font-mono text-[0.64rem] uppercase tracking-[0.12em] text-signal">Weaknesses</p>
                        <ul className="mt-2 grid gap-1 text-[0.88rem] text-fg-2">
                          {c.weaknesses.map((s) => (
                            <li key={s}>− {s}</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                    {c.pricingModel ? <p className="mt-3 text-[0.82rem] text-fg-3">Pricing: {c.pricingModel}</p> : null}
                  </div>
                ))}
              </div>
              <Sub>Table stakes</Sub>
              <Bullets items={run.research.tableStakes} />
              <Sub>Where to differentiate</Sub>
              <Bullets items={run.research.differentiationOpportunities} />
              <Sub>Positioning</Sub>
              <p className="rounded-2xl border border-signal/40 bg-signal-soft p-5 text-[1rem] leading-relaxed text-fg">{run.research.ourPositioning}</p>
            </Section>

            <Section id="prd" n="03" title="Product requirements document" lead={allRationales ? "Every feature carries a rationale tied back to the memo or the research." : "Features sorted into Must, Should, Could and Won't, exactly as the run returned them."}>
              <Sub>One-liner</Sub>
              <p className="font-display text-xl font-semibold leading-snug tracking-[-0.015em] text-fg">{run.prd.oneLiner}</p>
              {run.prd.problem ? (
                <>
                  <Sub>Problem</Sub>
                  <p className="text-[0.98rem] leading-relaxed text-fg-2">{run.prd.problem}</p>
                </>
              ) : null}
              <Sub>Target user</Sub>
              <p className="text-[0.98rem] leading-relaxed text-fg-2">{run.prd.targetUser}</p>
              <FeatureList label="Must have" items={run.prd.features.must_have} tone="must" />
              <FeatureList label="Should have" items={run.prd.features.should_have} tone="should" />
              <FeatureList label="Could have" items={run.prd.features.could_have} tone="could" />
              <FeatureList label="Won't have" items={run.prd.features.wont_have} tone="wont" />
              {run.prd.successMetrics.length ? (
                <>
                  <Sub>Success metrics</Sub>
                  <div className="overflow-hidden rounded-2xl border border-line">
                    <table className="w-full text-left text-[0.92rem]">
                      <thead className="bg-surface-2 font-mono text-[0.66rem] uppercase tracking-[0.1em] text-fg-3">
                        <tr>
                          <th className="px-4 py-3 font-medium">Metric</th>
                          <th className="px-4 py-3 font-medium">Target</th>
                        </tr>
                      </thead>
                      <tbody>
                        {run.prd.successMetrics.map((m) => (
                          <tr key={m.metric} className="border-t border-line align-top">
                            <td className="px-4 py-3 font-medium text-fg">{m.metric}</td>
                            <td className="px-4 py-3 text-fg-2">{m.target}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </>
              ) : null}
              {run.prd.nonGoals.length ? (
                <>
                  <Sub>Non-goals</Sub>
                  <Bullets items={run.prd.nonGoals} />
                </>
              ) : null}
              {run.prd.risks.length ? (
                <>
                  <Sub>Risks</Sub>
                  <Bullets items={run.prd.risks} />
                </>
              ) : null}
              {run.prd.openQuestions.length ? (
                <>
                  <Sub>Open questions</Sub>
                  <Bullets items={run.prd.openQuestions} />
                </>
              ) : null}
            </Section>

            <CtaBand location="example_page" title={`Want a PRD like ${name}'s for your idea?`} />

            <Section id="brand" n="04" title="Brand kit" lead="Name notes, tagline, values, palette, type and a logo direction, written from the PRD.">
              <div className="grid gap-8 md:grid-cols-2">
                <BrandKit run={run} large />
                <div>
                  <p className="text-4xl leading-[1.05] text-fg" style={{ fontFamily: heading, fontWeight: 600 }}>
                    {run.brand.tagline}
                  </p>
                  <Sub>Brand values</Sub>
                  <div className="flex flex-wrap gap-2">
                    {run.brand.brandValues.map((v) => (
                      <span key={v} className="rounded-full border border-line px-3 py-1.5 text-sm text-fg-2">
                        {v}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
              {run.brand.colorPalette.semantic ? (
                <>
                  <Sub>Semantic colors</Sub>
                  <div className="flex flex-wrap gap-3">
                    {Object.entries(run.brand.colorPalette.semantic).map(([k, v]) => (
                      <span key={k} className="flex items-center gap-2 rounded-full border border-line py-1 pl-1 pr-3 text-sm text-fg-2">
                        <span className="size-6 rounded-full" style={{ background: v }} />
                        {k} <span className="font-mono text-xs text-fg-3">{v.toUpperCase()}</span>
                      </span>
                    ))}
                  </div>
                </>
              ) : null}
              <Sub>Name notes</Sub>
              <Bullets items={run.brand.nameNotes} />
              {run.brand.logoDirection ? (
                <>
                  <Sub>Logo direction</Sub>
                  <dl className="grid gap-3 text-[0.95rem]">
                    {run.brand.logoDirection.form ? (
                      <div>
                        <dt className="font-mono text-[0.66rem] uppercase tracking-[0.1em] text-fg-3">Form</dt>
                        <dd className="mt-1 text-fg-2">{run.brand.logoDirection.form}</dd>
                      </div>
                    ) : null}
                    {run.brand.logoDirection.style ? (
                      <div>
                        <dt className="font-mono text-[0.66rem] uppercase tracking-[0.1em] text-fg-3">Style</dt>
                        <dd className="mt-1 text-fg-2">{run.brand.logoDirection.style}</dd>
                      </div>
                    ) : null}
                    {run.brand.logoDirection.symbolConcept ? (
                      <div>
                        <dt className="font-mono text-[0.66rem] uppercase tracking-[0.1em] text-fg-3">Symbol concept</dt>
                        <dd className="mt-1 text-fg-2">{run.brand.logoDirection.symbolConcept}</dd>
                      </div>
                    ) : null}
                  </dl>
                  {run.brand.logoDirection.avoidances?.length ? (
                    <>
                      <Sub>Avoid</Sub>
                      <Bullets items={run.brand.logoDirection.avoidances} />
                    </>
                  ) : null}
                </>
              ) : null}
            </Section>

            <Section id="engineering" n="05" title="Tech design" lead="The engineering brief: architecture, data flow, data models, schema, stack and the first tasks.">
              {run.engineering.overview ? (
                <>
                  <Sub>Overview</Sub>
                  <p className="text-[0.98rem] leading-relaxed text-fg-2">{run.engineering.overview}</p>
                </>
              ) : null}
              {run.engineering.dataFlow ? (
                <>
                  <Sub>Data flow</Sub>
                  <p className="text-[0.98rem] leading-relaxed text-fg-2">{run.engineering.dataFlow}</p>
                </>
              ) : null}
              <Sub>Components</Sub>
              <div className="grid gap-3 sm:grid-cols-2">
                {run.engineering.components.map((c) => (
                  <div key={c.name} className="rounded-2xl border border-line bg-surface p-4">
                    <p className="font-medium text-fg">{c.name}</p>
                    {c.responsibility ? <p className="mt-1.5 text-[0.88rem] leading-relaxed text-fg-2">{c.responsibility}</p> : null}
                  </div>
                ))}
              </div>
              <Sub>Tech stack</Sub>
              <dl className="overflow-hidden rounded-2xl border border-line">
                {Object.entries(run.engineering.techStack).map(([k, v]) => (
                  <div key={k} className="grid gap-1 border-b border-line px-4 py-3 last:border-0 sm:grid-cols-[8rem_1fr] sm:gap-4">
                    <dt className="font-mono text-[0.7rem] uppercase tracking-[0.1em] text-fg-3">{k}</dt>
                    <dd className="text-[0.92rem] text-fg-2">
                      <span className="font-medium text-fg">{shortStack(v, 60)}</span>
                      {v.length > shortStack(v, 60).length + 2 ? <span className="block text-fg-3">{v}</span> : null}
                    </dd>
                  </div>
                ))}
              </dl>
              <Sub>Data models</Sub>
              <div className="grid gap-3 sm:grid-cols-2">
                {run.engineering.dataModels.map((m) => (
                  <div key={m.entity} className="rounded-2xl border border-line bg-surface p-4">
                    <p className="font-mono text-sm font-medium text-fg">{m.entity}</p>
                    <ul className="mt-2 grid gap-0.5 font-mono text-[0.75rem] text-fg-2">
                      {m.fields.slice(0, 8).map((f) => (
                        <li key={f.name} className="flex justify-between gap-3">
                          <span>{f.name}</span>
                          <span className="text-fg-3">{f.type}</span>
                        </li>
                      ))}
                      {m.fields.length > 8 ? <li className="text-fg-3">+{m.fields.length - 8} more</li> : null}
                    </ul>
                  </div>
                ))}
              </div>
              {run.engineering.schemaSqlExcerpt ? (
                <>
                  <Sub>SQL schema (excerpt)</Sub>
                  <pre className="overflow-x-auto rounded-2xl border border-line bg-surface-2 p-4 font-mono text-[0.78rem] leading-relaxed text-fg-2">
                    <code>{run.engineering.schemaSqlExcerpt}</code>
                  </pre>
                </>
              ) : null}
              <Sub>First engineering tasks</Sub>
              <ol className="grid gap-3">
                {run.engineering.tasks.map((t, i) => (
                  <li key={t.title} className="flex gap-4">
                    <span className="font-mono text-xs text-fg-3">{String(i + 1).padStart(2, "0")}</span>
                    <div>
                      <p className="font-medium text-fg">{t.title}</p>
                      <p className="mt-0.5 text-[0.9rem] leading-relaxed text-fg-2">{t.description}</p>
                    </div>
                  </li>
                ))}
              </ol>
              {run.engineering.openQuestions.length ? (
                <>
                  <Sub>Open engineering questions</Sub>
                  <Bullets items={run.engineering.openQuestions} />
                </>
              ) : null}
            </Section>

            <Section id="confluence" n="06" title="Confluence space" lead={`A new space named after the brand, with ${numberWord(run.confluence.pages.length)} pages written from the artifacts above.`}>
              <ol className="grid gap-2 sm:grid-cols-2">
                {run.confluence.pages.map((page) => (
                  <li key={page} className="flex items-center gap-3 rounded-xl border border-line bg-surface px-4 py-3 text-fg-2">
                    <span className="grid size-6 place-items-center rounded bg-[#1868db] text-[0.65rem] font-bold text-white">C</span>
                    {page}
                  </li>
                ))}
              </ol>
            </Section>

            <Section id="roadmap" n="07" title="Roadmap" lead="Every story is placed in one of three phases.">
              <ol className="grid gap-4 sm:grid-cols-3">
                {run.roadmap.map((p, i) => (
                  <li key={p.phase} className="rounded-2xl border border-line bg-surface p-5">
                    <p className="font-mono text-[0.66rem] uppercase tracking-[0.12em] text-fg-3">{["Now", "Next", "Later"][i]}</p>
                    <p className="mt-1 font-display text-2xl font-semibold tracking-[-0.03em]">Phase {p.phase}</p>
                    <p className="text-sm text-fg-2">{p.storyCount} stories</p>
                    <ul className="mt-4 grid gap-1 text-[0.85rem] text-fg-2">
                      {p.epics.map((e) => (
                        <li key={e}>· {e}</li>
                      ))}
                    </ul>
                  </li>
                ))}
              </ol>
            </Section>

            <Section id="jira" n="08" title="Jira board" lead={`A new Jira project (${run.jira.projectKey}) created in the owner's own Atlassian site: ${run.jira.epicCount} epics, ${run.jira.storyCount} stories.`}>
              <div className="grid gap-4">
                {run.jira.epics.map((epic) => (
                  <details key={epic.key} className="group rounded-2xl border border-line bg-surface" open={epic.stories.length > 0 && run.jira.epics.indexOf(epic) < 3}>
                    <summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3.5 [&::-webkit-details-marker]:hidden">
                      <span className="flex items-center gap-3">
                        <span className="rounded bg-[#6e5dc6]/15 px-1.5 py-0.5 font-mono text-[0.66rem] text-[#8f7ee7]">EPIC</span>
                        <span className="font-medium text-fg">{epic.title}</span>
                      </span>
                      <span className="font-mono text-xs text-fg-3">
                        {epic.stories.length} stories <span className="inline-block transition-transform group-open:rotate-180">⌄</span>
                      </span>
                    </summary>
                    {epic.stories.length ? (
                      <ul className="grid gap-1 border-t border-line px-4 py-3">
                        {epic.stories.map((s) => (
                          <li key={s.key} className="flex items-start justify-between gap-4 py-1 text-[0.9rem]">
                            <span className="text-fg-2">{s.title}</span>
                            <span className="shrink-0 font-mono text-[0.68rem] text-fg-3">
                              {s.key} · P{s.phase}
                            </span>
                          </li>
                        ))}
                      </ul>
                    ) : null}
                  </details>
                ))}
              </div>
            </Section>

            <CtaBand location="example_page" title="That was one memo. What's yours?" />

            <nav aria-label="More examples" className="flex flex-col gap-3 border-t border-line pt-8 sm:flex-row sm:items-center sm:justify-between">
              <Link href="/examples" className="text-sm text-fg-2 hover:text-fg">
                ← All examples
              </Link>
              <Link href={`/examples/${next.slug}`} className="group text-right">
                <span className="block font-mono text-[0.66rem] uppercase tracking-[0.12em] text-fg-3">Next example</span>
                <span className="font-display text-xl font-semibold tracking-[-0.02em] text-fg">
                  {shortName(next.title)} · {next.idea} <span className="inline-block transition-transform group-hover:translate-x-1">→</span>
                </span>
              </Link>
            </nav>
          </article>
        </div>
      </div>
    </PageShell>
  );
}
